# Generated by Django 5.2.3 on 2025-08-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_com_mensagem',
            new_name='Superlike',
        ),
    ]
