# Generated by Django 5.2.3 on 2025-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_like_com_mensagem_superlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidades',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='accounts.habilidades'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='linkeds',
            unique_together={('usuario1', 'usuario2')},
        ),
    ]
