# Generated by Django 5.2.3 on 2025-08-25 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_habilidades_user_customuser_habilidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='foto_perfil',
        ),
        migrations.CreateModel(
            name='AparelhoSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('numero_celular', models.CharField(max_length=15, unique=True)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacao_linkeds', models.BooleanField(default=True)),
                ('notificacao_mensagens', models.BooleanField(default=True)),
                ('notificacao_eventos', models.BooleanField(default=False)),
                ('notificacao_sons', models.BooleanField(default=True)),
                ('mostrar_status_online', models.BooleanField(default=True)),
                ('confirmacao_leitura', models.BooleanField(default=True)),
                ('visibilidade_perfil', models.BooleanField(default=True)),
                ('mostrar_curso', models.BooleanField(default=True)),
                ('distancia_maxima', models.IntegerField(default=50)),
                ('modo_escuro', models.BooleanField(default=False)),
                ('tamanho_fonte', models.CharField(choices=[('small', 'Pequena'), ('medium', 'Média'), ('large', 'Grande')], default='medium', max_length=10)),
                ('idioma', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en-us', 'English (US)'), ('es', 'Español')], default='pt-br', max_length=10)),
                ('backup_automatico', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_usuario/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('foto_perfil', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', '-data_upload'],
            },
        ),
    ]
