# Generated by Django 5.2.3 on 2025-08-25 18:46

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_foto_perfil_aparelhosms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=48)),
                ('horario', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('manha', 'Manhã - 06h-12h'), ('tarde', 'Tarde - 12h-18h'), ('noite', 'Noite - 18h-00h')], max_length=17)),
                ('metodo_preferido', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('online', 'Estudo online'), ('presencial', 'Encontros presenciais'), ('grupo', 'Grupos de estudo')], max_length=23)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_estudo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
