# Generated by Django 5.2.3 on 2025-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_preferenciasestudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='semestre',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
