# Generated by Django 5.2.3 on 2025-08-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='celular',
            field=models.CharField(blank=True, default='Não informado', max_length=20),
        ),
    ]
