# Generated by Django 5.2.3 on 2025-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='universidade_nome',
            field=models.CharField(default='Não informado', max_length=200),
        ),
    ]
