# Generated by Django 5.2.3 on 2025-08-27 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_populate_university_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeEstudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('dias_encontros', models.CharField(help_text='Comma-separated list of weekday numbers (0=Sunday, 6=Saturday)', max_length=50)),
                ('horario_encontros', models.CharField(max_length=100)),
                ('localizacao_encontros', models.CharField(blank=True, max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('maximo_membros', models.PositiveIntegerField(default=5)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembroGrupoEstudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='accounts.grupodeestudos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'grupo')},
            },
        ),
    ]
