# Generated by Django 5.2.3 on 2025-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_grupodeestudos_membrogrupoestudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelhosms',
            name='token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
