# Generated by Django 5.2.3 on 2025-09-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_aparelhosms_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoesusuario',
            name='notificacao_eventos_grupos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracoesusuario',
            name='notificacao_matchs',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RelatorioProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('bug', 'Bug / Erro no Sistema'), ('ui', 'Problema de Interface'), ('performance', 'Problema de Performance'), ('login', 'Problema de Login/Acesso'), ('notification', 'Problema com Notificações'), ('match', 'Problema com Matches'), ('profile', 'Problema com Perfil'), ('messaging', 'Problema com Mensagens'), ('other', 'Outro Problema')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('dispositivo', models.CharField(blank=True, max_length=150)),
                ('frequencia', models.CharField(blank=True, choices=[('always', 'Sempre acontece'), ('often', 'Acontece frequentemente'), ('sometimes', 'Acontece às vezes'), ('rare', 'Acontece raramente'), ('once', 'Aconteceu apenas uma vez')], max_length=20)),
                ('prioridade', models.CharField(blank=True, choices=[('critical', 'Crítica - Não consigo usar o app'), ('high', 'Alta - Afeta funcionalidades importantes'), ('medium', 'Média - Inconveniente mas posso contornar'), ('low', 'Baixa - Sugestão de melhoria')], max_length=20)),
                ('incluir_contato', models.BooleanField(default=False)),
                ('email_usuario', models.EmailField(blank=True, max_length=254)),
                ('nome_usuario', models.CharField(blank=True, max_length=100)),
                ('arquivos_anexados', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em Análise'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_problema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Problema',
                'verbose_name_plural': 'Relatórios de Problema',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
